# GitHub Sponsors username
#github: []

# Ko-fi username
#ko_fi: 

# Buy Me a Coffee username
#buy_me_a_coffee:

# Patreon username
#patreon:

# Open Collective
#open_collective:

# Custom funding URLs
#custom:
#  - 